# Generated by Django 5.1.5 on 2025-02-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('visual_reference', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journeys.journey')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
